# Generated by Django 4.0.3 on 2022-04-28 18:28

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_comment_created_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='created_date',
            field=models.DateField(default=datetime.datetime(2022, 4, 28, 18, 28, 53, 952717, tzinfo=utc)),
        ),
    ]
